service: notes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  authorizer:
    handler: src/auth.authorizer
    environment:
      COGNITO_USER_POOL_ID: !Ref userPool
      COGNITO_WEB_CLIENT: !Ref userPoolWebClient

  getNote:
    handler: src/handler.getNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: get
          path: /notes/{id}
          authorizer:
            name: userpool_authorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt userPool.Arn
            # arn: ${ssm:/notes/${self:provider.stage}/userPoolArn}

  getNotes:
    handler: src/handler.getNotes
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:scan
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: get
          path: /notes
          authorizer:
            name: userpool_authorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt userPool.Arn
            # arn: ${ssm:/notes/${self:provider.stage}/userPoolArn}

  createNote:
    handler: src/handler.createNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: post
          path: /notes
          authorizer: authorizer

  updateNote:
    handler: src/handler.updateNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: put
          path: /notes/{id}
          authorizer: authorizer

  deleteNote:
    handler: src/handler.deleteNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: delete
          path: /notes/{id}
          authorizer: authorizer

plugins:
  - serverless-iam-roles-per-function

# CloudFormation resource
resources:
  Resources: ${file(resources.yml)}
